### ISSUE TITLE
How add symbol %

### ISSUE THREAD

**Issue by Fabszn** [delowardev/vue3-circle-progress#10]
How add '%' symbol behing percentage value ? 

I saw in first example that value at center of circle is equals to '55%'.

Thanks in advance

**Comment by eincipientinfo** [comment]
Hey Did you find the solution?

**Comment by samculo** [comment]
```css
<style lang="scss">
    .current-counter {
        &::after {
            content: "%";
        }
    }
</style>
```
